/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.app;

import static org.example.app.KotlinTestKt.KotlinEntryFunction;


import java.util.logging.Logger;

public class App {


    public static void main(String[] args) {
        Logger logger = Logger.getLogger("Main ");

        logger.info(KotlinEntryFunction());

//        LinkedList tokens;
//        tokens = split(getMessage());
//        String result = join(tokens);
//
//        logger.info(WordUtils.capitalize(result));
    }
}
